#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

(cd buoyMesh && ./Allclean)
(cd backgroundAndBuoy && ./Allclean)

#------------------------------------------------------------------------------
