#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

# Mesh buoy
echo "-----> START buoy meshing"
(cd buoyMesh && ./Allrun.pre)
echo "-----> END buoy meshing"

# Add background mesh and prepare case
echo "-----> START background meshing and case preparation"
(cd backgroundAndBuoy && ./Allrun.pre)
echo "-----> END background meshing and case preparation"
#------------------------------------------------------------------------------
